<?php

namespace Database\Seeders;

use App\Models\Festival;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FestivalSeeder extends Seeder
{
    public function run(): void
    {
        $festivals = [
            [
                'api_id' => 1001,
                'name' => 'Sundance Film Festival',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-09-15'),
                'opening_date' => Carbon::parse('2026-06-01'),
                'submission_fee' => 85.00,
                'accepting_submissions' => true,
                'festival_score' => 95,
                'details' => ['genres' => ['drama', 'indie', 'documentary']],
            ],
            [
                'api_id' => 1002,
                'name' => 'Cannes Film Festival',
                'category' => 'feature',
                'country' => 'France',
                'deadline' => Carbon::parse('2026-08-01'),
                'opening_date' => Carbon::parse('2026-05-01'),
                'submission_fee' => 150.00,
                'accepting_submissions' => true,
                'festival_score' => 98,
                'details' => ['genres' => ['art-house', 'drama', 'international']],
            ],
            [
                'api_id' => 1003,
                'name' => 'Toronto International Film Festival',
                'category' => 'feature',
                'country' => 'Canada',
                'deadline' => Carbon::parse('2026-07-20'),
                'opening_date' => Carbon::parse('2026-06-15'),
                'submission_fee' => 75.00,
                'accepting_submissions' => true,
                'festival_score' => 92,
                'details' => ['genres' => ['drama', 'documentary', 'indie']],
            ],
            [
                'api_id' => 1004,
                'name' => 'Berlin International Film Festival',
                'category' => 'feature',
                'country' => 'Germany',
                'deadline' => Carbon::parse('2026-08-15'),
                'opening_date' => Carbon::parse('2026-02-01'),
                'submission_fee' => 120.00,
                'accepting_submissions' => true,
                'festival_score' => 90,
                'details' => ['genres' => ['art-house', 'drama', 'documentary']],
            ],
            [
                'api_id' => 1005,
                'name' => 'SXSW Film Festival',
                'category' => 'short_film',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-08-30'),
                'opening_date' => Carbon::parse('2026-03-01'),
                'submission_fee' => 45.00,
                'accepting_submissions' => true,
                'festival_score' => 85,
                'details' => ['genres' => ['indie', 'documentary', 'experimental']],
            ],
            [
                'api_id' => 1006,
                'name' => 'Tribeca Film Festival',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-09-01'),
                'opening_date' => Carbon::parse('2026-04-01'),
                'submission_fee' => 65.00,
                'accepting_submissions' => true,
                'festival_score' => 88,
                'details' => ['genres' => ['drama', 'documentary', 'indie']],
            ],
            [
                'api_id' => 1007,
                'name' => 'Venice Film Festival',
                'category' => 'feature',
                'country' => 'Italy',
                'deadline' => Carbon::parse('2026-08-10'),
                'opening_date' => Carbon::parse('2026-08-01'),
                'submission_fee' => 100.00,
                'accepting_submissions' => true,
                'festival_score' => 96,
                'details' => ['genres' => ['art-house', 'drama', 'international']],
            ],
            [
                'api_id' => 1008,
                'name' => 'Fantasia International Film Festival',
                'category' => 'horror',
                'country' => 'Canada',
                'deadline' => Carbon::parse('2026-08-20'),
                'opening_date' => Carbon::parse('2026-07-01'),
                'submission_fee' => 40.00,
                'accepting_submissions' => true,
                'festival_score' => 78,
                'details' => ['genres' => ['horror', 'fantasy', 'sci-fi']],
            ],
            [
                'api_id' => 1009,
                'name' => 'Annecy International Animation Film Festival',
                'category' => 'animation',
                'country' => 'France',
                'deadline' => Carbon::parse('2026-09-30'),
                'opening_date' => Carbon::parse('2026-06-01'),
                'submission_fee' => 55.00,
                'accepting_submissions' => true,
                'festival_score' => 89,
                'details' => ['genres' => ['animation', 'family', 'indie']],
            ],
            [
                'api_id' => 1010,
                'name' => 'Hot Docs Canadian International Documentary Festival',
                'category' => 'documentary',
                'country' => 'Canada',
                'deadline' => Carbon::parse('2026-09-05'),
                'opening_date' => Carbon::parse('2026-04-01'),
                'submission_fee' => 50.00,
                'accepting_submissions' => true,
                'festival_score' => 84,
                'details' => ['genres' => ['documentary']],
            ],
            [
                'api_id' => 1011,
                'name' => 'Sitges Film Festival',
                'category' => 'horror',
                'country' => 'Spain',
                'deadline' => Carbon::parse('2026-09-10'),
                'opening_date' => Carbon::parse('2026-10-01'),
                'submission_fee' => 60.00,
                'accepting_submissions' => true,
                'festival_score' => 82,
                'details' => ['genres' => ['horror', 'fantasy', 'sci-fi']],
            ],
            [
                'api_id' => 1012,
                'name' => 'Clermont-Ferrand International Short Film Festival',
                'category' => 'short_film',
                'country' => 'France',
                'deadline' => Carbon::parse('2026-10-15'),
                'opening_date' => Carbon::parse('2027-02-01'),
                'submission_fee' => 35.00,
                'accepting_submissions' => true,
                'festival_score' => 86,
                'details' => ['genres' => ['short_film', 'animation', 'experimental']],
            ],
            [
                'api_id' => 1013,
                'name' => 'Rotterdam International Film Festival',
                'category' => 'feature',
                'country' => 'Netherlands',
                'deadline' => Carbon::parse('2026-09-20'),
                'opening_date' => Carbon::parse('2027-01-01'),
                'submission_fee' => 70.00,
                'accepting_submissions' => true,
                'festival_score' => 87,
                'details' => ['genres' => ['art-house', 'documentary', 'indie']],
            ],
            [
                'api_id' => 1014,
                'name' => 'Locarno Film Festival',
                'category' => 'feature',
                'country' => 'Switzerland',
                'deadline' => Carbon::parse('2026-09-25'),
                'opening_date' => Carbon::parse('2026-08-01'),
                'submission_fee' => 80.00,
                'accepting_submissions' => true,
                'festival_score' => 88,
                'details' => ['genres' => ['art-house', 'drama', 'international']],
            ],
            [
                'api_id' => 1015,
                'name' => 'Fribourg International Film Festival',
                'category' => 'feature',
                'country' => 'Switzerland',
                'deadline' => Carbon::parse('2026-10-01'),
                'opening_date' => Carbon::parse('2027-03-01'),
                'submission_fee' => 45.00,
                'accepting_submissions' => true,
                'festival_score' => 75,
                'details' => ['genres' => ['drama', 'documentary', 'indie']],
            ],
            [
                'api_id' => 1016,
                'name' => 'New York Film Festival',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-09-30'),
                'opening_date' => Carbon::parse('2026-09-01'),
                'submission_fee' => 90.00,
                'accepting_submissions' => true,
                'festival_score' => 91,
                'details' => ['genres' => ['art-house', 'drama', 'indie']],
            ],
            [
                'api_id' => 1017,
                'name' => 'Los Angeles Film Festival',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-08-25'),
                'opening_date' => Carbon::parse('2026-06-01'),
                'submission_fee' => 55.00,
                'accepting_submissions' => true,
                'festival_score' => 83,
                'details' => ['genres' => ['indie', 'documentary', 'drama']],
            ],
            [
                'api_id' => 1018,
                'name' => 'South by Southwest (SXSW) Conference',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-10-10'),
                'opening_date' => Carbon::parse('2027-03-01'),
                'submission_fee' => 75.00,
                'accepting_submissions' => true,
                'festival_score' => 85,
                'details' => ['genres' => ['indie', 'documentary', 'experimental', 'music']],
            ],
            [
                'api_id' => 1019,
                'name' => 'Edinburgh International Film Festival',
                'category' => 'feature',
                'country' => 'United Kingdom',
                'deadline' => Carbon::parse('2026-09-15'),
                'opening_date' => Carbon::parse('2026-08-01'),
                'submission_fee' => 50.00,
                'accepting_submissions' => true,
                'festival_score' => 79,
                'details' => ['genres' => ['drama', 'documentary', 'indie', 'horror']],
            ],
            [
                'api_id' => 1020,
                'name' => 'Melbourne International Film Festival',
                'category' => 'feature',
                'country' => 'Australia',
                'deadline' => Carbon::parse('2026-10-20'),
                'opening_date' => Carbon::parse('2027-08-01'),
                'submission_fee' => 55.00,
                'accepting_submissions' => true,
                'festival_score' => 81,
                'details' => ['genres' => ['drama', 'documentary', 'indie', 'horror']],
            ],
            [
                'api_id' => 1021,
                'name' => 'Sundance Film Festival (Short Film)',
                'category' => 'short_film',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-09-25'),
                'opening_date' => Carbon::parse('2026-06-01'),
                'submission_fee' => 50.00,
                'accepting_submissions' => true,
                'festival_score' => 92,
                'details' => ['genres' => ['short_film', 'indie', 'documentary']],
            ],
            [
                'api_id' => 1022,
                'name' => 'Vancouver International Film Festival',
                'category' => 'feature',
                'country' => 'Canada',
                'deadline' => Carbon::parse('2026-10-05'),
                'opening_date' => Carbon::parse('2027-09-01'),
                'submission_fee' => 45.00,
                'accepting_submissions' => true,
                'festival_score' => 77,
                'details' => ['genres' => ['drama', 'documentary', 'indie', 'international']],
            ],
            [
                'api_id' => 1023,
                'name' => 'Bristol Documentary Film Festival',
                'category' => 'documentary',
                'country' => 'United Kingdom',
                'deadline' => Carbon::parse('2026-10-15'),
                'opening_date' => Carbon::parse('2027-06-01'),
                'submission_fee' => 35.00,
                'accepting_submissions' => true,
                'festival_score' => 74,
                'details' => ['genres' => ['documentary']],
            ],
            [
                'api_id' => 1024,
                'name' => 'Slamdance Film Festival',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-10-30'),
                'opening_date' => Carbon::parse('2027-01-01'),
                'submission_fee' => 40.00,
                'accepting_submissions' => true,
                'festival_score' => 80,
                'details' => ['genres' => ['indie', 'experimental', 'documentary']],
            ],
            [
                'api_id' => 1025,
                'name' => 'Dead by Dawn',
                'category' => 'horror',
                'country' => 'United Kingdom',
                'deadline' => Carbon::parse('2026-10-01'),
                'opening_date' => Carbon::parse('2027-04-01'),
                'submission_fee' => 30.00,
                'accepting_submissions' => true,
                'festival_score' => 72,
                'details' => ['genres' => ['horror']],
            ],
            [
                'api_id' => 1026,
                'name' => 'Fantasia Film Festival',
                'category' => 'sci_fi',
                'country' => 'Canada',
                'deadline' => Carbon::parse('2026-10-15'),
                'opening_date' => Carbon::parse('2027-07-01'),
                'submission_fee' => 45.00,
                'accepting_submissions' => true,
                'festival_score' => 76,
                'details' => ['genres' => ['sci-fi', 'fantasy', 'horror', 'animation']],
            ],
            [
                'api_id' => 1027,
                'name' => 'Hawaii International Film Festival',
                'category' => 'feature',
                'country' => 'United States',
                'deadline' => Carbon::parse('2026-10-20'),
                'opening_date' => Carbon::parse('2026-10-01'),
                'submission_fee' => 50.00,
                'accepting_submissions' => true,
                'festival_score' => 78,
                'details' => ['genres' => ['drama', 'documentary', 'international', 'horror']],
            ],
            [
                'api_id' => 1028,
                'name' => 'Cannes Short Film Corner',
                'category' => 'short_film',
                'country' => 'France',
                'deadline' => Carbon::parse('2026-09-15'),
                'opening_date' => Carbon::parse('2026-05-01'),
                'submission_fee' => 40.00,
                'accepting_submissions' => true,
                'festival_score' => 88,
                'details' => ['genres' => ['short_film', 'animation']],
            ],
            [
                'api_id' => 1029,
                'name' => 'Milan International Filmmaker Festival',
                'category' => 'feature',
                'country' => 'Italy',
                'deadline' => Carbon::parse('2026-11-01'),
                'opening_date' => Carbon::parse('2027-01-01'),
                'submission_fee' => 55.00,
                'accepting_submissions' => true,
                'festival_score' => 73,
                'details' => ['genres' => ['drama', 'art-house', 'indie']],
            ],
            [
                'api_id' => 1030,
                'name' => 'Tokyo International Film Festival',
                'category' => 'feature',
                'country' => 'Japan',
                'deadline' => Carbon::parse('2026-10-10'),
                'opening_date' => Carbon::parse('2026-10-01'),
                'submission_fee' => 60.00,
                'accepting_submissions' => true,
                'festival_score' => 84,
                'details' => ['genres' => ['drama', 'documentary', 'international', 'anime']],
            ],
        ];

        foreach ($festivals as $festival) {
            Festival::firstOrCreate(
                ['api_id' => $festival['api_id']],
                $festival
            );
        }

        $this->command->info('Created ' . Festival::count() . ' festivals');
    }
}
